[package]
name = "dbdata_to_excel"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "mssql-experimental", "macros"] }
xlsxwriter = "0.6"